# Super Claude Configuration
# Super Claude Flag System Integration
# Full integration with existing Constitutional AI system

version: "1.0.0"
name: "Super Claude Integration Layer"
description: "Super Claude extension layer maintaining 100% existing system"

# Flag mapping configuration
flags:
  react:
    flag: "--react"
    description: "Enable realtime monitoring"
    system_component: "src/monitoring/realtime_monitoring_system.py"
    activation_command: "make monitor-realtime"
    enforcement_level: "mandatory"
    
  magic:
    flag: "--magic"
    description: "Enable autonomous growth engine"
    system_component: "src/ai/autonomous_growth_engine.py"
    activation_command: "make ai-growth"
    enforcement_level: "enhanced"
    
  watch:
    flag: "--watch"
    description: "Enable violation monitoring"
    system_component: "src/monitoring/realtime_violation_monitor.py"
    activation_command: "make monitor-violations"
    enforcement_level: "strict"
    
  persona:
    flag: "--persona"
    description: "Dynamic persona system"
    system_component: "src/ai/dynamic_role_system.py"
    activation_command: "make ai-persona"
    parameters_allowed: true

# Persona template configuration
personas:
  available:
    - frontend_specialist
    - backend_specialist
    - architecture_specialist
    - security_specialist
    - devops_specialist
    - data_specialist
    - testing_specialist
    - documentation_specialist
    - problem_analysis_specialist
  
  default: "architecture_specialist"
  template_path: "src/agents/templates/super_claude/personas/"

# Integration with existing systems
integration:
  constitutional_ai:
    enabled: true
    integration_point: "src/ai/constitutional_ai.py"
    
  memory_system:
    enabled: true
    integration_point: "src/memory/breakthrough_memory_system.py"
    
  monitoring:
    enabled: true
    realtime_log: "runtime/super_claude_flags.log"
    
# Security configuration
security:
  require_president_declaration: true
  enforce_rbac: true
  audit_logging: true

# Extension configuration
extensions:
  web_ui:
    enabled: true
    port: 3000
    path: "src/web-ui/"
    
  api_endpoints:
    enabled: true
    base_path: "/api/super-claude"