#!/usr/bin/env python3
"""
Slack通知スクリプト - タスク状況を投稿
"""
import os
import requests
import json
from datetime import datetime

def send_slack_notification():
    token = os.getenv('SLACK_BOT_TOKEN')
    if not token:
        print("❌ SLACK_BOT_TOKEN not found")
        return False
    
    # タスクサマリーを読み込み
    try:
        with open('/tmp/task_summary.md', 'r', encoding='utf-8') as f:
            task_content = f.read()
    except FileNotFoundError:
        task_content = "タスクサマリーファイルが見つかりません"
    
    message = f"""
🤖 **Claude Code タスク状況レポート** 
📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{task_content}

---
📝 Generated by Claude Code Task Management System
    """
    
    url = "https://slack.com/api/chat.postMessage"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "channel": "#general",  # または適切なチャンネル
        "text": message,
        "username": "Claude Code Bot",
        "icon_emoji": ":robot_face:"
    }
    
    try:
        response = requests.post(url, headers=headers, json=payload)
        result = response.json()
        
        if result.get('ok'):
            print("✅ Slack通知送信成功")
            return True
        else:
            print(f"❌ Slack通知失敗: {result.get('error', 'Unknown error')}")
            return False
    except Exception as e:
        print(f"❌ Slack通知エラー: {e}")
        return False

if __name__ == "__main__":
    send_slack_notification()